"""Generated bytes only: never performs network or opens EEG."""
import hashlib
import importlib.util
import io
import json
import sys
from pathlib import Path

import pytest

SCRIPTS = Path(__file__).resolve().parents[1] / "scripts" / "analysis"
sys.path.insert(0, str(SCRIPTS))
spec = importlib.util.spec_from_file_location("mamem_fetch", SCRIPTS / "fetch_mamem_i_archives_v1.py")
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)


def test_exact_copy():
    out = io.BytesIO()
    n, md5, sha = module.copy_payload(io.BytesIO(b"sample"), out, 6, 2)
    assert n == 6 and out.getvalue() == b"sample"
    assert md5 == hashlib.md5(b"sample").hexdigest()
    assert sha == hashlib.sha256(b"sample").hexdigest()


@pytest.mark.parametrize("payload", [b"short", b"toolong"])
def test_size_fail(payload):
    with pytest.raises(module.Stop):
        module.copy_payload(io.BytesIO(payload), io.BytesIO(), 6, 2)


def test_reserve():
    module.reserve_check(15, 6, 8, 1)
    with pytest.raises(module.Stop):
        module.reserve_check(14, 6, 8, 1)


@pytest.mark.parametrize("url", ["http://ndownloader.figshare.com/x",
                                    "https://example.com/file", "https://u:p@ndownloader.figshare.com/x"])
def test_disallowed_url(url):
    assert not module.allowed_url(url)


def test_guarded_writer(monkeypatch):
    state = {"remaining": 6, "deadline": 10}
    monkeypatch.setattr(module.shutil, "disk_usage", lambda _: type("Disk", (), {"free": 15})())
    out = io.BytesIO()
    writer = module.GuardedWriter(out, "/unused", state,
                                  {"reserve_bytes": 8, "extraction_bytes": 1}, clock=lambda: 0)
    writer.write(b"ab")
    assert state["remaining"] == 4 and out.getvalue() == b"ab"
    monkeypatch.setattr(module.shutil, "disk_usage", lambda _: type("Disk", (), {"free": 12})())
    with pytest.raises(module.Stop):
        writer.write(b"c")
    assert state["remaining"] == 4 and out.getvalue() == b"ab"


def test_deadline_before_write(monkeypatch):
    state = {"remaining": 1, "deadline": 1}
    out = io.BytesIO()
    writer = module.GuardedWriter(out, "/unused", state,
                                  {"reserve_bytes": 0, "extraction_bytes": 0}, clock=lambda: 2)
    with pytest.raises(module.Stop):
        writer.write(b"x")
    assert not out.getvalue()


def test_expired_manifest_no_network(tmp_path, monkeypatch):
    path = tmp_path / "manifest.json"
    path.write_text(json.dumps({"frozen_at_utc": "2020-01-01T00:00:00+00:00",
                               "overall_deadline_utc": "2020-01-01T01:00:00+00:00"}))
    calls = []
    monkeypatch.setattr(module.urllib.request, "build_opener", lambda *a: calls.append(a))
    with pytest.raises(module.Stop, match="manifest_expired_no_network"):
        module.run(path)
    assert not calls


def test_outer_interruption_has_receipt_and_start(tmp_path):
    specs = [{"id": 1, "name": "generated.rar", "bytes": 3}]
    result = {"records": []}
    cancelled = []

    def interrupt(*args):
        raise module.Stop("generated_outer_alarm")

    module.acquisition(specs, tmp_path, {}, {}, result, lambda: cancelled.append(True), interrupt)
    assert cancelled == [True]
    receipt = json.loads((tmp_path / "acquisition.json").read_text())
    assert receipt["status"] == "STOPPED_NO_RETRY"
    assert receipt["outer_reason"] == "generated_outer_alarm"
    assert json.loads((tmp_path / "acquisition.jsonl").read_text())["status"] == "STARTED"


def test_overall_deadline_limits_manifest():
    manifest = {"frozen_at_utc": "2020-01-01T00:00:00+00:00",
                "overall_deadline_utc": "2020-01-01T00:10:00+00:00"}
    assert module.remaining_seconds(manifest, 1577836800) == 600
