"""Fixed artificial learning and selection isolation; no efficacy dataset."""

from dataclasses import fields, replace

import numpy as np
import pytest
import torch

from cfeg.analysis import task_trca_n1_learning as learning
from cfeg.analysis import task_trca_n1_signfree as signfree
from cfeg.analysis.task_trca_n1_batch import TaskBatch


def make_case(pid=1001, role="fit", *, missing=False):
    rng = np.random.default_rng(73)
    # Both people are generated by this one frozen stream, not searched seeds.
    if pid % 2 == 0:
        rng.normal(size=123)
    prototype = rng.normal(size=(12, 5, 8, 17))
    support = prototype[None] + rng.normal(size=(3, 12, 5, 8, 17))
    source = prototype + rng.normal(size=prototype.shape)
    packet = np.full((3, 8), np.nan) if missing else rng.uniform(0, 20, (3, 8))
    return learning.make_task_case(
        pid,
        0,
        0,
        support,
        packet,
        np.linspace(9, 14.5, 12),
        source,
        role=role,
        weights=np.ones(5),
    )


@pytest.fixture(scope="module")
def trained():
    original = torch.get_num_threads()
    torch.set_num_threads(1)
    cases = (make_case(), make_case(1002))
    model = learning.fit_pipeline(cases, 0.001)
    yield cases, model
    torch.set_num_threads(original)


def test_actual_fixed_optimizer_and_frozen_q(trained):
    cases, model = trained
    assert model.q.coefficients.shape == (16,)
    assert model.q.final_loss < model.q.initial_loss
    before = model.q_hash
    for arm, fitted in model.residuals.items():
        assert arm in learning.RESIDUAL_ARMS
        assert fitted.coefficients.shape == (3,)
        assert len(fitted.trace) == 200
        assert np.isfinite([r["gradient_norm"] for r in fitted.trace]).all()
        assert max(r["gradient_norm"] for r in fitted.trace) > 1e-12
        assert np.max(np.abs(fitted.coefficients)) > 1e-12
    assert len(model.q.trace) == 200
    assert max(r["gradient_norm"] for r in model.q.trace) > 1e-12
    assert np.max(np.abs(model.q.coefficients)) > 1e-12
    for arm in ("Q", *learning.RESIDUAL_ARMS, "PERMUTED", "STALE", "MISSING", "ISO"):
        scored = learning.predict(model, cases, arm)
        assert all(v.shape == (12, 12) and np.isfinite(v).all() for v in scored.values())
    assert model.q_hash == before
    assert model.fit_ids == (1001, 1002)
    assert model.record()["q_hash"] == before
    assert model.record()["schema"] == learning.SCHEMA == "task-trca-n1-integration-v1"
    assert (
        model.record()["score_schema"]
        == learning.SCORE_SCHEMA
        == "component-time-centered-ensemble-pearson-v1"
    )
    assert model.schema == learning.SCHEMA and model.score_schema == learning.SCORE_SCHEMA


def test_missing_and_zero_residual_exact_q(trained):
    cases, model = trained
    q = learning.predict(model, cases, "Q")
    absent = learning.predict(model, cases, "MISSING")
    for key in q:
        np.testing.assert_array_equal(q[key], absent[key])
    zero = replace(model.residuals["QM"], coefficients=np.zeros(3))
    zero_model = replace(model, residuals={**model.residuals, "QM": zero})
    for key, values in learning.predict(zero_model, cases, "QM").items():
        np.testing.assert_array_equal(values, q[key])


def test_training_denies_validation_and_outer_overlap(trained):
    cases, _ = trained
    with pytest.raises(PermissionError):
        learning.fit_pipeline((replace(cases[0], role="validation"),), 0.001)
    with pytest.raises(PermissionError):
        learning.nested_fit(cases, outer_evaluation_ids=(1001,))
    with pytest.raises(ValueError, match="grid"):
        learning.fit_pipeline(cases, 1.0)
    with pytest.raises(ValueError, match="Duplicate"):
        learning.fit_pipeline((cases[0], cases[0]), 0.001)


def test_eval_builder_rejects_before_array_conversion():
    class Poison:
        def __array__(self, *args, **kwargs):
            raise AssertionError("Evaluation block5 was touched")

    with pytest.raises(PermissionError):
        learning.make_task_case(
            1, 0, 0, Poison(), Poison(), Poison(), Poison(), role="evaluation", weights=np.ones(5)
        )


def test_choose_lambda_ignores_all_metadata_validation_outcomes():
    rows = [
        {
            "lambda": value,
            "inner_fold": fold,
            "validation_ids": [fold],
            "validation_ce": {"Q": 1.0, "QM": float("nan")},
        }
        for value in learning.LAMBDAS
        for fold in range(3)
    ]
    assert learning.choose_lambda(rows) == 0.01
    for r in rows:
        r["validation_ce"]["Q"] = {0.0001: 0.5, 0.001: 0.7, 0.01: 0.9}[r["lambda"]]
        r["validation_ce"]["QM"] = -1e20 if r["lambda"] == 0.01 else 1e20
    assert learning.choose_lambda(rows) == 0.0001


def test_prediction_donor_roles_cannot_mix_or_leak(trained):
    cases, model = trained
    with pytest.raises(PermissionError, match="Mixed roles"):
        learning.predict(model, (cases[0], replace(cases[1], role="validation")), "SHAM_REFIT")
    with pytest.raises(PermissionError, match="overlap"):
        learning.predict(model, tuple(replace(c, role="validation") for c in cases), "PERMUTED")
    with pytest.raises(PermissionError, match="complete fitted donor"):
        learning.predict(model, (cases[0],), "SHAM_REFIT")
    with pytest.raises(ValueError):
        model.q.coefficients.setflags(write=True)


@pytest.mark.parametrize("field", ["support", "packet", "source", "weights"])
@pytest.mark.parametrize("dtype", [complex, str, bool, object])
def test_builder_rejects_dtype_before_coercion(field, dtype):
    rng = np.random.default_rng(73)
    values = {
        "support": rng.normal(size=(3, 12, 5, 8, 17)),
        "packet": np.ones((3, 8)),
        "source": rng.normal(size=(12, 5, 8, 17)),
        "weights": np.ones(5),
    }
    values[field] = values[field].astype(dtype)
    with pytest.raises(ValueError, match="real"):
        learning.make_task_case(
            1,
            0,
            0,
            values["support"],
            values["packet"],
            np.linspace(9, 14.5, 12),
            values["source"],
            weights=values["weights"],
        )


def test_nested_entire_fit_graph_rebuilt_with_disjoint_people(monkeypatch, trained):
    cases, _ = trained
    # Structural graph test with a fit spy, not an actual nested efficacy run.
    expanded = tuple(replace(cases[0], participant_id=pid) for pid in range(1001, 1007))
    fits = []

    class Fitted:
        def __init__(self, ids, lam):
            self.ids, self.lam = ids, lam

        def record(self):
            return {"fit_ids": list(self.ids)}

    def fit(rows, lam):
        assert all(c.role == "fit" for c in rows)
        ids = tuple(sorted(c.participant_id for c in rows))
        fits.append((ids, lam))
        return Fitted(ids, lam)

    def val(model, rows, arm):
        assert all(c.role == "validation" for c in rows)
        assert not set(model.ids) & {c.participant_id for c in rows}
        return 1.0 if arm == "Q" else -model.lam

    monkeypatch.setattr(learning, "fit_pipeline", fit)
    monkeypatch.setattr(learning, "validation_ce", val)
    model, receipt = learning.nested_fit(expanded, outer_evaluation_ids=(2001,))
    assert len(fits) == 10 and len(receipt["inner"]) == 9
    assert receipt["schema"] == learning.SCHEMA
    assert receipt["score_schema"] == learning.SCORE_SCHEMA
    assert receipt["selected_lambda"] == 0.01
    assert len(model.ids) == 6
    for row in receipt["inner"]:
        assert len(row["fit_ids"]) == 4 and len(row["validation_ids"]) == 2


def test_no_available_metadata_neutral_scalers_and_zero_residuals():
    original = torch.get_num_threads()
    torch.set_num_threads(1)
    try:
        case = make_case(missing=True)
        model = learning.fit_pipeline((case,), 0.001)
        for scaler in (model.m_scaler, model.q2_scaler):
            np.testing.assert_array_equal(scaler.mean, np.zeros(2))
            np.testing.assert_array_equal(scaler.scale, np.ones(2))
        q = learning.predict(model, (case,), "Q")[case.key]
        for arm in learning.RESIDUAL_ARMS:
            np.testing.assert_array_equal(model.residuals[arm].coefficients, np.zeros(3))
            assert len(model.residuals[arm].trace) == 200
            np.testing.assert_array_equal(learning.predict(model, (case,), arm)[case.key], q)
    finally:
        torch.set_num_threads(original)


def test_legacy_case_statistics_and_pipeline_rejected(trained):
    from cfeg.analysis import task_trca_shape_learning as legacy
    from cfeg.analysis.task_trca_shape_operator import GramStatistics

    cases, model = trained
    case = cases[0]
    global_statistics = GramStatistics(
        case.statistics.query_gram,
        case.statistics.template_gram,
        case.statistics.cross_gram,
        torch.zeros((12, 5, 8), dtype=torch.float64),
        torch.zeros((12, 5, 8), dtype=torch.float64),
        case.samples,
    )
    with pytest.raises(TypeError, match="legacy/global"):
        replace(case, statistics=global_statistics)
    legacy_case = legacy.TaskCase(
        **{field.name: getattr(case, field.name) for field in fields(case)}
    )
    with pytest.raises(ValueError, match="TaskCase"):
        learning.fit_pipeline((legacy_case,), 0.001)
    legacy_model = legacy.Pipeline(
        **{field.name: getattr(model, field.name) for field in fields(model)}
    )
    with pytest.raises(TypeError, match="legacy/global"):
        learning.predict(legacy_model, cases)


def test_native_anchor_values_never_change_positive_loss_or_scores(trained):
    cases, model = trained
    changed = tuple(replace(c, anchors=c.anchors * -37) for c in cases)
    for arm in ("ISO", "Q", "Q2", "QM", "SHAM_REFIT", "PERMUTED", "STALE", "MISSING"):
        original = learning.predict(model, cases, arm)
        other = learning.predict(model, changed, arm)
        for key in original:
            np.testing.assert_array_equal(original[key], other[key])
    coefficient = torch.linspace(-0.1, 0.1, 16, dtype=torch.float64, requires_grad=True)
    qx = learning._as_tensor(model.q_scaler.transform(cases[0].q), "cpu")
    logits = learning._head(qx, coefficient, 0.8)
    loss = learning._ce(learning._prior_scores(cases[0], logits), cases[0])
    other_loss = learning._ce(learning._prior_scores(changed[0], logits), changed[0])
    gradient = torch.autograd.grad(loss, coefficient, retain_graph=True)[0]
    other_gradient = torch.autograd.grad(other_loss, coefficient)[0]
    torch.testing.assert_close(loss, other_loss, rtol=0, atol=0)
    torch.testing.assert_close(gradient, other_gradient, rtol=0, atol=0)


def test_head_gradient_matches_finite_difference(trained):
    cases, model = trained
    case = cases[0]
    qx = learning._as_tensor(model.q_scaler.transform(case.q), "cpu")
    coefficient = torch.linspace(-0.07, 0.09, 16, dtype=torch.float64, requires_grad=True)

    def loss(value):
        return learning._ce(learning._prior_scores(case, learning._head(qx, value, 0.8)), case)

    gradient = torch.autograd.grad(loss(coefficient), coefficient)[0]
    for index in (0, 1, 2, 7, 15):
        step = torch.zeros_like(coefficient)
        step[index] = 1e-5
        difference = (loss(coefficient.detach() + step) - loss(coefficient.detach() - step)) / 2e-5
        torch.testing.assert_close(gradient[index], difference, rtol=2e-4, atol=2e-8)
    assert gradient.abs().max() > 1e-7


def test_donors_are_condition_local_cyclic_and_do_not_use_numeric_m(trained):
    cases, model = trained
    assert model.donor_ids[cases[0].key] == cases[1].participant_id
    assert model.donor_ids[cases[1].key] == cases[0].participant_id
    assert not np.array_equal(cases[0].m, cases[1].m)
    changed = []
    for c in cases:
        packet = learning._readonly(c.packet * (10 + c.participant_id) + 5)
        m, available = learning.features.metadata_features(packet)
        changed.append(
            replace(
                c,
                packet=packet,
                m=learning._readonly(m),
                available=learning._readonly(available, bool),
            )
        )
    assert learning._donors(changed) == model.donor_ids
    # Altering the exact prefix mask, not numerical magnitude, separates strata.
    c = cases[1]
    packet = np.array(c.packet)
    packet[0, 0] = np.nan
    m, available = learning.features.metadata_features(packet)
    separated = replace(
        c,
        packet=learning._readonly(packet),
        m=learning._readonly(m),
        available=learning._readonly(available, bool),
        mask=learning._readonly(np.isfinite(packet), bool),
    )
    donors = learning._donors((cases[0], separated))
    assert donors == {c.key: c.participant_id for c in (cases[0], separated)}


def test_validation_scaling_is_frozen_and_fit_q_has_no_numeric_m_input(trained):
    cases, model = trained
    case = replace(cases[0], participant_id=2001, role="validation")
    before = model.q_hash
    correct = learning.predict(model, (case,), "Q")[case.key]
    packet = learning._readonly(case.packet * 1e8)
    m, available = learning.features.metadata_features(packet)
    changed = replace(
        case, packet=packet, m=learning._readonly(m), available=learning._readonly(available, bool)
    )
    np.testing.assert_array_equal(learning.predict(model, (changed,), "Q")[case.key], correct)
    assert model.q_hash == before
    assert (
        model.q_scaler.fit_ids == model.m_scaler.fit_ids == model.q2_scaler.fit_ids == model.fit_ids
    )


@pytest.mark.parametrize("value", [(1, 1), (False,), (-1,), (1.0,)])
def test_invalid_outer_role_ids_reject_before_fitting(trained, value):
    cases, _ = trained
    with pytest.raises(ValueError, match="unique positive"):
        learning.nested_fit(cases, outer_evaluation_ids=value)


@pytest.mark.parametrize("field", ["m", "mask", "available"])
def test_case_packet_consistency_guard(trained, field):
    cases, _ = trained
    value = np.array(getattr(cases[0], field))
    value.flat[0] = not value.flat[0] if value.dtype == bool else value.flat[0] + 1
    with pytest.raises(ValueError, match="Metadata/mask/available"):
        learning.fit_pipeline((replace(cases[0], **{field: value}),), 0.001)


def test_actual_four_head_200_step_scalar_batch_parity(trained):
    cases, scalar = trained
    batch = learning.fit_pipeline(cases, 0.001, backend="batch")
    for name, left, right in [("Q", scalar.q, batch.q)] + [
        (arm, scalar.residuals[arm], batch.residuals[arm]) for arm in learning.RESIDUAL_ARMS
    ]:
        assert len(left.trace) == len(right.trace) == 200
        assert max(row["gradient_norm"] for row in right.trace) > 1e-12
        assert np.max(np.abs(right.coefficients)) > 1e-12
        np.testing.assert_allclose(left.coefficients, right.coefficients, atol=1e-8, rtol=0)
        np.testing.assert_allclose(left.final_loss, right.final_loss, atol=1e-8, rtol=0)
        # No artificial efficacy ordering is required among the four heads.
        a, b = learning.predict(scalar, cases, name), learning.predict(batch, cases, name)
        for key in a:
            np.testing.assert_allclose(a[key], b[key], atol=1e-8, rtol=0)
            np.testing.assert_array_equal(a[key].argmax(-1), b[key].argmax(-1))


def mixed_cases():
    rng = np.random.default_rng(73)
    cases = []
    for pid in (12001, 12002):
        packet = rng.uniform(0, 30, (5, 8))
        packet[:, 2] = np.nan
        for samples in (17, 23):
            proto = rng.normal(size=(12, 5, 8, samples)) + 0.7
            support = proto[None] + rng.normal(size=(5, 12, 5, 8, samples))
            source = proto + rng.normal(size=proto.shape)
            for k in (3, 5):
                cases.append(
                    learning.make_task_case(
                        pid,
                        0,
                        0,
                        support[:k],
                        packet[:k],
                        np.linspace(9, 14.5, 12),
                        source,
                        weights=np.linspace(1.3, 0.4, 5) * (1 + k / 20),
                        labels=np.roll(np.arange(12), pid % 12),
                    )
                )
    return tuple(cases)


def test_mixed_windows_budgets_unsorted_batch_loss_and_gradient():
    cases = tuple(reversed(mixed_cases()))
    logits = torch.linspace(-0.2, 0.2, len(cases) * 40, dtype=torch.float64).reshape(-1, 5, 8)
    logits.requires_grad_()
    batch = TaskBatch(cases)
    actual = batch.scores(logits)
    expected = torch.stack([learning._prior_scores(c, logits[j]) for j, c in enumerate(cases)])
    torch.testing.assert_close(actual, expected, atol=1e-8, rtol=0)
    loss = batch.loss(logits)
    reference = torch.stack([learning._ce(expected[j], c) for j, c in enumerate(cases)]).mean()
    ga = torch.autograd.grad(loss, logits, retain_graph=True)[0]
    gr = torch.autograd.grad(reference, logits)[0]
    torch.testing.assert_close(loss, reference, atol=1e-8, rtol=0)
    torch.testing.assert_close(ga, gr, atol=1e-8, rtol=0)
    assert ga.abs().max() > 1e-12
    assert batch.samples == tuple(c.samples for c in cases)
    assert set(batch.stats) == {"query_gram", "template_gram", "cross_gram"}


def test_nested_packet_prefix_and_batch_case_geometry():
    cases = mixed_cases()
    bad = cases[0]
    packet = np.array(bad.packet) + 1
    m, available = learning.features.metadata_features(packet)
    bad = replace(
        bad,
        packet=learning._readonly(packet),
        m=learning._readonly(m),
        available=learning._readonly(available, bool),
    )
    with pytest.raises(ValueError, match="Metadata identity"):
        TaskBatch((bad, *cases[1:]))
    # Change BOTH windows at k=3, so only the nested k=3/k=5 identity fails.
    altered = []
    for case in cases:
        if case.participant_id == bad.participant_id and case.k == 3:
            altered.append(replace(case, packet=bad.packet, m=bad.m, available=bad.available))
        else:
            altered.append(case)
    with pytest.raises(ValueError, match="prefix"):
        TaskBatch(altered)
    with pytest.raises(ValueError, match="sample counts"):
        replace(cases[0], samples=19)
    with pytest.raises(ValueError, match="common grid"):
        TaskBatch(cases[:-1])


@pytest.mark.parametrize("device", ["cuda", "meta"])
def test_cpu_only_before_array_conversion(device):
    class Poison:
        def __array__(self, *args, **kwargs):
            raise AssertionError("non-CPU input must not be converted")

    with pytest.raises(ValueError, match="CPU-only"):
        learning.make_task_case(
            1, 0, 0, Poison(), Poison(), Poison(), Poison(), weights=Poison(), device=device
        )
    with pytest.raises(ValueError, match="CPU-only"):
        learning._fit_head(2, lambda x: x.sum(), 0.001, device)


def test_old_temporal_types_rejected(trained):
    from cfeg.analysis import task_trca_temporal_learning as old

    cases, model = trained
    with pytest.raises(ValueError, match="TaskCase"):
        TaskBatch((old.TaskCase(**vars(cases[0])),))
    old_model = old.Pipeline(
        **{
            **vars(model),
            "q": old.HeadFit(**vars(model.q)),
            "residuals": {
                name: old.HeadFit(**vars(head)) for name, head in model.residuals.items()
            },
        }
    )
    with pytest.raises(TypeError):
        learning.predict(old_model, cases)


def test_n1_original_inputs_exact_tau_and_detached_diagnostics(trained):
    case = trained[0][0]
    logits = torch.linspace(-0.2, 0.2, 40, dtype=torch.float64).reshape(5, 8).requires_grad_()
    r = learning.operator.shape_prior(logits)
    f = signfree.bounded_projectors(case.s, case.c, r[:, None])
    tau = 0.1 * torch.linalg.eigvalsh((case.c + case.c.mT) / 2)[..., 0] / (16 / 9)
    b = case.c + torch.diag_embed(tau[..., None] * r[:, None])
    expected = signfree.numerical.projector(case.s, b, case.c, "N1_SYM_CHOLESKY")
    torch.testing.assert_close(f, expected, atol=0, rtol=0)
    info = signfree.diagnostics(case.s, case.c, r[:, None], f)
    assert set(info) == {
        "lambda",
        "residual",
        "normalization_error",
        "symmetry_error",
        "raw_h_skew",
        "normalization_ratio",
    }
    assert all(not value.requires_grad and torch.isfinite(value).all() for value in info.values())
    assert (info["residual"] <= 1e-12).all()
    assert (info["normalization_ratio"] >= 1 / 1.1 - 1e-10).all()
    scores = signfree.score_temporal_gram(f, case.statistics, case.weights)[0]
    gradient = torch.autograd.grad(learning._ce(scores, case), logits)[0]
    assert gradient.abs().max() > 1e-12
    # Same forward values with a detached F cannot satisfy the gradient oracle.
    detached = signfree.score_temporal_gram(f.detach(), case.statistics, case.weights)[0]
    wrong = learning._ce(detached, case) + logits.sum() * 0
    wrong_gradient = torch.autograd.grad(wrong, logits)[0]
    assert torch.count_nonzero(wrong_gradient) == 0
    assert not torch.allclose(gradient, wrong_gradient, atol=1e-12, rtol=0)


@pytest.mark.parametrize(
    "bad", ["s_skew", "c_skew", "finite", "spd", "gap", "live_s", "live_c", "prior", "broadcast"]
)
def test_n1_adapter_guards(bad):
    c = torch.eye(8, dtype=torch.float64)
    s = torch.diag(torch.arange(8, dtype=torch.float64))
    r = torch.ones(8, dtype=torch.float64)
    if bad == "s_skew":
        s *= 1e-8
        s[0, 1] = 1e-13  # Old max(norm,1) would hide this; N1 must reject.
    elif bad == "c_skew":
        c *= 1e-8
        c[0, 1] = 1e-13
    elif bad == "finite":
        s[0, 0] = torch.nan
    elif bad == "spd":
        c[0, 0] = 0
    elif bad == "gap":
        s = c.clone()
    elif bad == "live_s":
        s.requires_grad_()
    elif bad == "live_c":
        c.requires_grad_()
    elif bad == "prior":
        r[0] = 2
    elif bad == "broadcast":
        r = torch.ones(2, 8, dtype=torch.float64)
    with pytest.raises(ValueError):
        signfree.bounded_projectors(s, c, r)


def test_normalization_bound_sensitivity():
    c = torch.eye(8, dtype=torch.float64)
    f = c / 8
    with pytest.raises(ValueError, match="bounded-denominator"):
        signfree._normalization_ratio(c, 2 * c, f)
    with pytest.raises(ValueError, match="positive"):
        signfree._normalization_ratio(c, -c, f)


def test_accepted_tiny_raw_skew_is_preserved_in_denominator():
    c = torch.eye(8, dtype=torch.float64)
    c[0, 1] = 1e-14
    s = torch.diag(torch.arange(8, dtype=torch.float64))
    r = torch.ones(8, dtype=torch.float64)
    b = signfree._denominator(s, c, r)
    assert b[0, 1] == c[0, 1] and b[1, 0] == c[1, 0]
    assert b[0, 1] != b[1, 0]
    f = signfree.bounded_projectors(s, c, r)
    info = signfree.diagnostics(s, c, r, f)
    assert (info["residual"] <= 1e-12).all()


def test_scalar_batch_native_anchors_do_not_change_gradient(trained):
    cases = trained[0]
    altered = tuple(replace(c, anchors=torch.zeros_like(c.anchors)) for c in cases)
    logits = torch.linspace(-0.2, 0.2, len(cases) * 40, dtype=torch.float64).reshape(-1, 5, 8)
    logits.requires_grad_()
    left, right = TaskBatch(cases), TaskBatch(altered)
    torch.testing.assert_close(left.scores(logits), right.scores(logits), atol=0, rtol=0)
    ga = torch.autograd.grad(left.loss(logits), logits)[0]
    gb = torch.autograd.grad(right.loss(logits), logits)[0]
    torch.testing.assert_close(ga, gb, atol=0, rtol=0)


@pytest.mark.parametrize("bad", ["shape", "dtype", "finite", "bounds"])
def test_batch_bad_logits_rejected(trained, bad):
    batch = TaskBatch(trained[0])
    logits = torch.zeros(batch.cases, 5, 8, dtype=torch.float64)
    if bad == "shape":
        logits = logits[:1]
    elif bad == "dtype":
        logits = logits.float()
    elif bad == "finite":
        logits[0, 0, 0] = torch.nan
    else:
        logits[0, 0, 0] = 1
    with pytest.raises(ValueError):
        batch.scores(logits)


def test_batch_zero_projected_variance_remains_a_failure(trained):
    case = trained[0][0]
    zero = replace(case.statistics, query_gram=torch.zeros_like(case.statistics.query_gram))
    with pytest.raises(ValueError, match="variance"):
        TaskBatch((replace(case, statistics=zero),))
